service: template-node-serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  memorySize: ${env:MEMORY_SIZE}
  timeout: ${env:TIMEOUT}
  environment:
    NODE_ENV: ${env:STAGE}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

functions:
  - ${file(functions.yml)}
